### ISSUE TITLE
Push message on change

### ISSUE THREAD

**Issue by Graefer** [Matten-Matten/node-red-enigma2-flow#2]
Nice subflow in order to send commands or to get some information! I would like to make the subflow push a message, i.e. if the Dreambox' power state changed. Any way?

**Comment by Matten-Matten** [comment]
Verstehe ich das richtig, du möchtest das der SUBFlow eine Nachricht sendet? An den Receiver oder wohin soll die Nachricht gehen? 
Oder meinst du, das du eine Info vom SUBFlow erhalten möchtest wenn der Receiver in den Standby aus dem Standby geht?

**Comment by Graefer** [comment]
Ich hätte gerne, dass der Subflow einen Output (0 bzw. 1 als Payload) hat, der durch Standby-Statusänderung getriggert wird. Der Hintergrund: Ich möchte gerne, dass bei Einschalten der Dreambox über Fernbedienung z.B. die Rollos heruntergelassen werden und dem Homekit-Objekt der aktuelle Status zugewiesen wird. 
Grüße

**Comment by Matten-Matten** [comment]
Das Kannst du über den output 1 (Einschaltstatus) machen und folgendes dahinter hängen
![Program Manager-29 06 2020_15_45_09](https://user-images.githubusercontent.com/32074970/86013597-9d0f4e80-ba1f-11ea-8157-ccb799cb66d3.png)

Flow:
`[{"id":"efe67285.46e08","type":"change","z":"8ee283de.e0c71","name":"umformen","rules":[{"t":"change","p":"payload","pt":"msg","from":"true","fromt":"bool","to":"1","tot":"num"},{"t":"change","p":"payload","pt":"msg","from":"false","fromt":"bool","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":1000,"y":220,"wires":[["27c27226.c7d93e"]]},{"id":"27c27226.c7d93e","type":"debug","z":"8ee283de.e0c71","name":"Einschaltstatus","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":1180,"y":220,"wires":[]}]`

**Comment by Matten-Matten** [comment]
Hast du damit dein Wunsch nachkommen können?

**Comment by Graefer** [comment]
Herzlichen Dank für die Nachfrage. Urlaubsbedingt konnte ich das noch nicht ausprobieren. Aber ich hatte früher schon diese Idee gehabt, mit einem Debug-Node aber darüber keinen Output bekommen. Ich werde das aber lieber nochmal ausprobieren bevor ich mich festlege, dass das nicht funktioniert.

**Comment by Graefer** [comment]
Jetzt habe ich mich nochmal mit dem Subflow beschäftigt. Mein Fehler war, dass sich das Polling ausgeschaltet hatte und deswegen keine Werte mehr bekam. Jetzt ist es eingeschaltet  - und ich kann meine Dreambox mit HomeKit ein- und ausschalten. Wunderbar!

**Comment by Matten-Matten** [comment]
Ja super, dann.viel Spaß und gutes Gelingen mit dem Subflow.

Ich mache hier zu.
